/*
 * Copyright (C) 2018 David Barry <david.barry at crick dot ac dot uk>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ui;

import RatiometricAssay.Ratiometric_Assay;
import UtilClasses.GenUtils;
import ij.IJ;
import ij.ImagePlus;
import ij.ImageStack;

/**
 *
 * @author David Barry <david.barry at crick dot ac dot uk>
 */
public class SegUI extends javax.swing.JFrame {

    private double maskBlurRadius;
    private String threshMethod;
    private int holeSize;
    private ImagePlus imp;
    private ImageStack stack1, stack2;

    /**
     * Creates new form NewJFrame
     */
    public SegUI() {
        this(1.0, "Triangle", 10);
    }

    public SegUI(double maskBlurRadius, String threshMethod, int holeSize) {
        this.maskBlurRadius = maskBlurRadius;
        this.threshMethod = threshMethod;
        this.holeSize = holeSize;
        getStacks();
        initComponents();
    }

    final void getStacks() {
        if (IJ.getInstance() == null) {
            stack1 = IJ.openImage().getImageStack();
            stack2 = IJ.openImage().getImageStack();
        } else {
            ImagePlus[] imps = GenUtils.specifyInputs(new String[]{"Stack 1", "Stack 2"});
            stack1 = imps[0].getImageStack();
            stack2 = imps[1].getImageStack();
        }
        if (stack1.size() != stack2.size()
                || stack1.getWidth() != stack2.getWidth()
                || stack1.getHeight() != stack2.getHeight()) {
            GenUtils.error("Stack dimensions must match.");
        }
    }

    void setVariables() {
        this.maskBlurRadius = Double.parseDouble(blurTextField.getText());
        this.threshMethod = (String) threshComboBox.getSelectedItem();
        this.holeSize = Integer.parseInt(holeSizeTextField.getText());
    }

    public double getMaskBlurRadius() {
        return maskBlurRadius;
    }

    public String getThreshMethod() {
        return threshMethod;
    }

    public int getHoleSize() {
        return holeSize;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cancelButton = new javax.swing.JButton();
        previewButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        threshLabel = new javax.swing.JLabel();
        threshComboBox = new javax.swing.JComboBox<>();
        holeSizeTextField = new javax.swing.JTextField();
        holeSizeLabel = new javax.swing.JLabel();
        blurLabel = new javax.swing.JLabel();
        blurTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(71, 75, 2, 0);
        getContentPane().add(cancelButton, gridBagConstraints);

        previewButton.setText("Preview");
        previewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(71, 37, 2, 0);
        getContentPane().add(previewButton, gridBagConstraints);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(71, 21, 2, 0);
        getContentPane().add(okButton, gridBagConstraints);

        threshLabel.setText("Thresholding Method");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(74, 0, 0, 0);
        getContentPane().add(threshLabel, gridBagConstraints);

        threshComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Ratiometric_Assay.THRESH_METHODS));
        threshComboBox.setSelectedItem(threshMethod);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 258;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(71, 0, 0, 0);
        getContentPane().add(threshComboBox, gridBagConstraints);

        holeSizeTextField.setText(String.valueOf(holeSize));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 280;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(71, 0, 0, 0);
        getContentPane().add(holeSizeTextField, gridBagConstraints);

        holeSizeLabel.setText("Hole Size");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(74, 0, 0, 0);
        getContentPane().add(holeSizeLabel, gridBagConstraints);

        blurLabel.setText("Blur Radius");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(blurLabel, gridBagConstraints);

        blurTextField.setText(String.valueOf(maskBlurRadius));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 280;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        getContentPane().add(blurTextField, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cleanUp();
        System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void previewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewButtonActionPerformed
        setVariables();
        imp = new ImagePlus("Preview Segmentation", Ratiometric_Assay.makeBinaryStack(stack1, maskBlurRadius, threshMethod, holeSize));
        imp.show();
    }//GEN-LAST:event_previewButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        setVariables();
        cleanUp();
        new Ratiometric_Assay().analyse(stack1, stack2);
        System.exit(0);
    }//GEN-LAST:event_okButtonActionPerformed
    void cleanUp() {
        if (imp != null) {
            imp.close();
        }
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SegUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SegUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SegUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SegUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SegUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blurLabel;
    private javax.swing.JTextField blurTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel holeSizeLabel;
    private javax.swing.JTextField holeSizeTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JButton previewButton;
    private javax.swing.JComboBox<String> threshComboBox;
    private javax.swing.JLabel threshLabel;
    // End of variables declaration//GEN-END:variables
}
